[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/tirzepatida"
  to = "/produto.html"
  status = 200

[[redirects]]
  from = "/tesamorelin"
  to = "/produto.html"
  status = 200

[[redirects]]
  from = "/cjc-1295-ipamorelin"
  to = "/produto.html"
  status = 200

[[redirects]]
  from = "/mots-c"
  to = "/produto.html"
  status = 200

[[redirects]]
  from = "/ipamorelin"
  to = "/produto.html"
  status = 200

[[redirects]]
  from = "/bpc-157"
  to = "/produto.html"
  status = 200

[[redirects]]
  from = "/tb-500"
  to = "/produto.html"
  status = 200

[[redirects]]
  from = "/ghk-cu"
  to = "/produto.html"
  status = 200

[[redirects]]
  from = "/kpv"
  to = "/produto.html"
  status = 200

[[redirects]]
  from = "/5-amino-1mq"
  to = "/produto.html"
  status = 200

[[redirects]]
  from = "/pt-141"
  to = "/produto.html"
  status = 200
